In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np 
import pandas as pd 
import os
import glob
import time
import pandas as pd

from nltk import ngrams
from nltk.tokenize import sent_tokenize
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.stem import PorterStemmer
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [3]:
from google.colab import files

df = pd.read_csv("/content/drive/MyDrive/sqli.csv",encoding='utf-16')
df

Sentence  Label
0                                                     a      1
1                                                   a'       1
2                                                 a' --      1
3                                       a' or 1 = 1; --      1
4                                                     @      1
...                                                 ...    ...
4195   org/?option = com_k2  <a href = "http://corfopym      0
4196  com/?option = com_k2  <act>  <![CDATA[procMemb...      0
4197                                          picsearch      0
4198  com/is?-WZx-uhyLezKNiYLvAbKL3W4oh5F749nr2KUmFF...      0
4199  de]]>  </email_address>   <find_account_answer...      0

[4200 rows x 2 columns]

In [8]:
df['Label'].value_counts()

0    3072
1    1128
Name: Label, dtype: int64

In [11]:

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer( min_df=2, max_df=0.7, stop_words=stopwords.words('english'))
posts = vectorizer.fit_transform(df['Sentence'].values.astype('U')).toarray()



In [13]:
posts

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [15]:
transformed_posts=pd.DataFrame(posts)
transformed_posts.head(10)

0     1     2     3     4     5     6     7     8     9     ...  4707  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   
5     0     0     0     0     0     0     0     0     0     0  ...     0   
6     0     0     0     0     0     0     0     0     0     0  ...     0   
7     0     0     0     0     0     0     0     0     0     0  ...     0   
8     0     0     0     0     0     0     0     0     0     0  ...     0   
9     0     0     0     0     0     0     0     0     0     0  ...     0   

   4708  4709  4710  4711  4712  4713  4714  4715  4716  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  
5     0     0     0     0     0     0     0     0     0  
6     0     0     0     0     0     0     0     0     0  
7     0     0     0     0     0     0     0     0     0  
8     0     0     0     0     0     0     0     0     0  
9     0     0     0     0     0     0     0     0     0  

[10 rows x 4717 columns]

In [17]:
df=pd.concat([df,transformed_posts],axis=1)
df.head(10)

Sentence  Label  0  1  2  3  4  5  6  7  ...  4707  4708  \
0                          a      1  0  0  0  0  0  0  0  0  ...     0     0   
1                        a'       1  0  0  0  0  0  0  0  0  ...     0     0   
2                      a' --      1  0  0  0  0  0  0  0  0  ...     0     0   
3            a' or 1 = 1; --      1  0  0  0  0  0  0  0  0  ...     0     0   
4                          @      1  0  0  0  0  0  0  0  0  ...     0     0   
5                          ?      1  0  0  0  0  0  0  0  0  ...     0     0   
6   ' and 1 = 0 )  union all      1  0  0  0  0  0  0  0  0  ...     0     0   
7              ? or 1 = 1 --      1  0  0  0  0  0  0  0  0  ...     0     0   
8  x' and userid is NULL; --      1  0  0  0  0  0  0  0  0  ...     0     0   
9   x' and email is NULL; --      1  0  0  0  0  0  0  0  0  ...     0     0   

   4709  4710  4711  4712  4713  4714  4715  4716  
0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0  
5     0     0     0     0     0     0     0     0  
6     0     0     0     0     0     0     0     0  
7     0     0     0     0     0     0     0     0  
8     0     0     0     0     0     0     0     0  
9     0     0     0     0     0     0     0     0  

[10 rows x 9436 columns]

In [18]:
X=df[df.columns[2:]]

In [19]:
y=df['Label']

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
X.head()

0     0     1     1     2     2     3     3     4     4     ...  4712  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   
3     0     0     0     0     0     0     0     0     0     0  ...     0   
4     0     0     0     0     0     0     0     0     0     0  ...     0   

   4712  4713  4713  4714  4714  4715  4715  4716  4716  
0     0     0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0     0     0  

[5 rows x 18868 columns]

In [ ]:
#Logistic Reegression

In [22]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(X_train, y_train)
from sklearn.metrics import accuracy_score
y_pred=clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.969047619047619

In [ ]:
# Naive Bayes

In [25]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, y_train)

pred_gnb = gnb.predict(X_test)

In [26]:
# SVM
from sklearn.svm import SVC
clf = SVC(gamma='auto')
clf.fit(X_train, y_train)
pred_svm=clf.predict(X_test)

In [27]:
# KNN
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

pred_knn = neigh.predict(X_test)

In [28]:
# DT
from sklearn import tree

dt = tree.DecisionTreeClassifier()
dt = dt.fit(X_train, y_train)

pred_dt = dt.predict(X_test)

In [29]:
def accuracy_function(tp,tn,fp,fn):
    
    accuracy = (tp+tn) / (tp+tn+fp+fn)
    
    return accuracy

def precision_function(tp,fp):
    
    precision = tp / (tp+fp)
    
    return precision

def recall_function(tp,fn):
    
    recall=tp / (tp+fn)
    
    return recall

def confusion_matrix(truth,predicted):
    
    true_positive = 0
    true_negative = 0
    false_positive = 0
    false_negative = 0
    
    for true,pred in zip(truth,predicted):
        
        if true == 1:
            if pred == true:
                true_positive += 1
            elif pred != true:
                false_negative += 1

        elif true == 0:
            if pred == true:
                true_negative += 1
            elif pred != true:
                false_positive += 1
            
    accuracy = accuracy_function(true_positive, true_negative, false_positive, false_negative)
    precision = precision_function(true_positive, false_positive)
    recall = recall_function(true_positive, false_negative)
    
    return (accuracy,precision,recall)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For Logistic Regression\n\n")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

For Logistic Regression


[[562  26]
 [  0 252]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       588
           1       0.91      1.00      0.95       252

    accuracy                           0.97       840
   macro avg       0.95      0.98      0.96       840
weighted avg       0.97      0.97      0.97       840

0.969047619047619


In [31]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For Logistic Regression")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))

For Logistic Regression
Accuracy: 0.969047619047619
Precision: 0.9064748201438849
Recall: 1.0


In [32]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For Gaussian Naive Bayes\n\n")
print(confusion_matrix(y_test, pred_gnb))
print(classification_report(y_test, pred_gnb))
print(accuracy_score(y_test, pred_gnb))

For Gaussian Naive Bayes


[[569  19]
 [  0 252]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98       588
           1       0.93      1.00      0.96       252

    accuracy                           0.98       840
   macro avg       0.96      0.98      0.97       840
weighted avg       0.98      0.98      0.98       840

0.9773809523809524


In [33]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For Naive Bayes")
print("Accuracy:",metrics.accuracy_score(y_test, pred_gnb))
print("Precision:",metrics.precision_score(y_test, pred_gnb))
print("Recall:",metrics.recall_score(y_test, pred_gnb))

For Naive Bayes
Accuracy: 0.9773809523809524
Precision: 0.9298892988929889
Recall: 1.0


In [34]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For Support Vector Machine\n\n")
print(confusion_matrix(y_test, pred_svm))
print(classification_report(y_test, pred_svm))
print(accuracy_score(y_test, pred_svm))

For Support Vector Machine


[[588   0]
 [198  54]]
              precision    recall  f1-score   support

           0       0.75      1.00      0.86       588
           1       1.00      0.21      0.35       252

    accuracy                           0.76       840
   macro avg       0.87      0.61      0.60       840
weighted avg       0.82      0.76      0.71       840

0.7642857142857142


In [35]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For Support Vecctor Machine")
print("Accuracy:",metrics.accuracy_score(y_test, pred_svm))
print("Precision:",metrics.precision_score(y_test, pred_svm))
print("Recall:",metrics.recall_score(y_test, pred_svm))

For Support Vecctor Machine
Accuracy: 0.7642857142857142
Precision: 1.0
Recall: 0.21428571428571427


In [36]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For K- Nearest Neighbor\n\n")
print(confusion_matrix(y_test, pred_knn))
print(classification_report(y_test, pred_knn))
print(accuracy_score(y_test, pred_knn))

For K- Nearest Neighbor


[[225 363]
 [  0 252]]
              precision    recall  f1-score   support

           0       1.00      0.38      0.55       588
           1       0.41      1.00      0.58       252

    accuracy                           0.57       840
   macro avg       0.70      0.69      0.57       840
weighted avg       0.82      0.57      0.56       840

0.5678571428571428


In [37]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For K- Nearest Neighbor")
print("Accuracy:",metrics.accuracy_score(y_test, pred_knn))
print("Precision:",metrics.precision_score(y_test, pred_knn))
print("Recall:",metrics.recall_score(y_test, pred_knn))

For K- Nearest Neighbor
Accuracy: 0.5678571428571428
Precision: 0.4097560975609756
Recall: 1.0


In [38]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For Decision Tree\n\n")
print(confusion_matrix(y_test, pred_dt))
print(classification_report(y_test, pred_dt))
print(accuracy_score(y_test, pred_dt))

For Decision Tree


[[488 100]
 [  0 252]]
              precision    recall  f1-score   support

           0       1.00      0.83      0.91       588
           1       0.72      1.00      0.83       252

    accuracy                           0.88       840
   macro avg       0.86      0.91      0.87       840
weighted avg       0.91      0.88      0.89       840

0.8809523809523809


In [39]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("For Decision Tree")
print("Accuracy:",metrics.accuracy_score(y_test, pred_dt))
print("Precision:",metrics.precision_score(y_test, pred_dt))
print("Recall:",metrics.recall_score(y_test, pred_dt))

For Decision Tree
Accuracy: 0.8809523809523809
Precision: 0.7159090909090909
Recall: 1.0


In [40]:
from keras.models import Sequential
from keras import layers
from keras.preprocessing.text import Tokenizer
from keras.wrappers.scikit_learn import KerasClassifier

In [41]:
input_dim = X_train.shape[1]  # Number of features

model = Sequential()
model.add(layers.Dense(20, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10,  activation='tanh'))
model.add(layers.Dense(1024, activation='relu'))

model.add(layers.BatchNormalization())
model.add(layers.Dropout(0.6))
model.add(layers.Dense(1, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 20)                94360     
                                                                 
 dense_1 (Dense)             (None, 10)                210       
                                                                 
 dense_2 (Dense)             (None, 1024)              11264     
                                                                 
 batch_normalization (BatchN  (None, 1024)             4096      
 ormalization)                                                   
                                                                 
 dropout (Dropout)           (None, 1024)              0         
                                                                 
 dense_3 (Dense)             (None, 1)                 1025      
                                                        

In [ ]:
classifier_nn = model.fit(X_train,y_train,
                    epochs=20,
                    verbose=True,
                    validation_data=(X_test, y_test),
                    batch_size=15)

Epoch 1/20
224/224 [==============================] - 2s 9ms/step - loss: 0.0776 - accuracy: 0.9696 - val_loss: 0.0639 - val_accuracy: 0.9762
Epoch 2/20
224/224 [==============================] - 2s 10ms/step - loss: 0.0830 - accuracy: 0.9720 - val_loss: 0.0543 - val_accuracy: 0.9786
Epoch 3/20
224/224 [==============================] - 2s 9ms/step - loss: 0.0819 - accuracy: 0.9693 - val_loss: 0.0962 - val_accuracy: 0.9714
Epoch 4/20
224/224 [==============================] - 2s 10ms/step - loss: 0.0825 - accuracy: 0.9696 - val_loss: 0.0711 - val_accuracy: 0.9786
Epoch 5/20
224/224 [==============================] - 2s 9ms/step - loss: 0.0723 - accuracy: 0.9753 - val_loss: 0.1431 - val_accuracy: 0.9655
Epoch 6/20
224/224 [==============================] - 2s 9ms/step - loss: 0.0789 - accuracy: 0.9711 - val_loss: 0.0752 - val_accuracy: 0.9774
Epoch 7/20
224/224 [==============================] - 2s 8ms/step - loss: 0.0770 - accuracy: 0.9711 - val_loss: 0.0592 - val_accuracy: 0.9786
Epoc

In [ ]:
pred=model.predict(X_test)

In [ ]:
for i in range(len(pred)):
    if pred[i]>0.5:
        pred[i]=1
    elif pred[i]<=0.5:
        pred[i]=0

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("For CNN Tree\n\n")
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))
print(accuracy_score(y_test, pred))

For CNN Tree


[[572  16]
 [  0 252]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       588
           1       0.94      1.00      0.97       252

    accuracy                           0.98       840
   macro avg       0.97      0.99      0.98       840
weighted avg       0.98      0.98      0.98       840

0.9809523809523809


In [ ]:
from sklearn import metrics
print("For CNN")
print("Accuracy:",metrics.accuracy_score(y_test, pred))
print("Precision:",metrics.precision_score(y_test, pred))
print("Recall:",metrics.recall_score(y_test, pred))

For CNN
Accuracy: 0.9809523809523809
Precision: 0.9402985074626866
Recall: 1.0
